### PR TITLE
fix broken whitespace on Control Structure - #12

### LINKED ISSUE #8: Deprecations on PHPCS Fixer 3.32.x
## Steps required to reproduce the problem

When using the `-vvv` option to see the rules used for #7. I saw some deprecations.

```
- Option "tokens: use_trait" used in `no_extra_blank_lines` rule is deprecated, use the rule `class_attributes_separation` with `elements: trait_import` instead.
- Rule "no_trailing_comma_in_list_call" is deprecated. Use "no_trailing_comma_in_singleline" instead.
- Rule "no_trailing_comma_in_singleline_array" is deprecated. Use "no_trailing_comma_in_singleline" instead.
```

### LINKED ISSUE #12: Wrong Whitespace on Control Structure
## Steps required to reproduce the problem

https://github.com/drupol/phpcsfixer-configs-drupal/issues/8#issuecomment-1764578190

Well I found the bug seems to be on Drupal/control_structure_braces_else.
This should move the else on the next line, but seems to break the indentation.

When unsetting, the issue is "fixed" (still the bracket is not moved to the next line so it's not realy fixed).

unset($rules['Drupal/control_structure_braces_else']);
Fixing this should also add a tests coverage on https://github.com/drupol/phpcsfixer-configs-drupal/blob/master/tests/functional/fixtures/scenario0/[good|bad.php]

## Expected Result

```
-    elseif ($limit) {
+   elseif ($limit) {
```

## Actual Result

```
-    elseif ($limit) {
+elseif ($limit) {
```

PR: #11

### PR DESCRIPTION
**Pull request by WengerK**
Fix the Fixer `Drupal/control_structure_braces_else` with newer way to handle whitespace on PHP-CS-Fixer.

See https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/2617

close #12

### CODE REVIEW

**Comment by FlorentTorregrosa** [comment]
Hi,

I have tested the MR on https://git.drupalcode.org/project/entity_share/-/blob/8.x-3.x/modules/entity_share_client/src/Plugin/EntityShareClient/Processor/PhysicalFile.php?ref_type=heads

Before:

```php
      if ($this->fileSystem->prepareDirectory($directory_uri, FileSystemInterface::CREATE_DIRECTORY)) {
        try {
          $response = $this->remoteManager->request($runtime_import_context->getRemote(), 'GET', $remote_file_url);
          $file_content = (string) $response->getBody();
          $result = @\file_put_contents($file_destination, $file_content);
          if (!$result) {
            throw new \Exception('Error writing file to ' . $file_destination);
          }
        }
catch (ClientException $e) {
          $this->logger->warning('Error importing file id %id. Missing file: %url', $log_variables);
          $this->messenger()->addWarning($this->t('Error importing file id %id. Missing file: %url', $log_variables));
        }
catch (\Throwable $e) {
          $log_variables['@msg'] = $e->getMessage();
          $this->logger->error('Caught exception trying to import the file %url to %uri. Error message was @msg', $log_variables);
          $this->messenger()->addError($this->t('Caught exception trying to import the file %url to %uri', $log_variables));
        }
      }
else {
        $this->logger->error('Impossible to write in the directory %directory', $log_variables);
        $this->messenger()->addError($this->t('Impossible to write in the directory %directory', $log_variables));
      }
```


After:

```php
      if ($this->fileSystem->prepareDirectory($directory_uri, FileSystemInterface::CREATE_DIRECTORY)) {
        try {
          $response = $this->remoteManager->request($runtime_import_context->getRemote(), 'GET', $remote_file_url);
          $file_content = (string) $response->getBody();
          $result = @\file_put_contents($file_destination, $file_content);
          if (!$result) {
            throw new \Exception('Error writing file to ' . $file_destination);
          }
        }
catch (ClientException $e) {
          $this->logger->warning('Error importing file id %id. Missing file: %url', $log_variables);
          $this->messenger()->addWarning($this->t('Error importing file id %id. Missing file: %url', $log_variables));
        }
catch (\Throwable $e) {
          $log_variables['@msg'] = $e->getMessage();
          $this->logger->error('Caught exception trying to import the file %url to %uri. Error message was @msg', $log_variables);
          $this->messenger()->addError($this->t('Caught exception trying to import the file %url to %uri', $log_variables));
        }
      }
      else {
        $this->logger->error('Impossible to write in the directory %directory', $log_variables);
        $this->messenger()->addError($this->t('Impossible to write in the directory %directory', $log_variables));
      }

```

**Comment by drupol** [comment]
Could you please make 2 commits within this PR ?

1. One commit with only the change you want
2. One commit with the style changes

**Comment by WengerK** [comment]
I saw the "try-catch" issue @FlorentTorregrosa - fixed here (https://github.com/WengerK/phpcsfixer-configs-drupal/pull/1/files#diff-09761387cfdd7fda6aab184e12003c108339847e5f0952fa651f9337772e6cf7)

I have started a huge PR that rewrite a lot of the dev-environemnt for DX purpose - especially having a better testing process that is up-to-date https://github.com/WengerK/phpcsfixer-configs-drupal/pull/1

I will have a chat with @drupol tomorrow (ping @FlorentTorregrosa) to discuss about the future of this PR and Project. How I can help maintain the project and if @drupol allow me to bring some changes on the project strategy (especially on the testing strategy that I try to improve but also drastically change).

**Comment by FlorentTorregrosa** [comment]
Thanks @WengerK for moving this forward!

**Pull request closed without merging**
