### PR TITLE
Issue #20: Enable declare_strict_types without spaces around equal for Drupal8.

### LINKED ISSUE #20: Enable declare_strict_types
## Steps required to reproduce the problem

In [Coder 8.3.23](https://www.drupal.org/project/coder/releases/8.3.23), adding declare strict types had been enabled: https://www.drupal.org/node/3407995

Change record: https://www.drupal.org/node/3402544

## Expected Result

```php
declare(strict_types=1);
```

## Actual Result

While the rule in [PHP CS Fixer](https://cs.symfony.com/doc/rules/strict/declare_strict_types.html) should be ok.

Enabling it like on https://gitlab.com/florenttorregrosa-drupal/docker-drupal-project/-/blob/10.x/scripts/quality/phpcs_fixer/.php-cs-fixer.dist.php?ref_type=heads, produces:

```php
declare(strict_types = 1);
```

Which is not ok for PHP CS.

## Proposed resolution

- enable strict types in the config provided by this repository, now that it has been added in Coder.
- change configuration of other PHP CS fixer plugins to not add the spaces around the equal in this case. Or create a custom plugin to add the strict_types like Coder wants.

### PR DESCRIPTION
**Pull request by FlorentTorregrosa**
This PR

Fixes #20 .

### CODE REVIEW

**Review by drupol — APPROVED** [review]
Finally! Bravo Drupal !

**Comment by FlorentTorregrosa** [comment]
I am not sure what to do about the failing grumphp task.

**Comment by drupol** [comment]
Have you tried: `./vendor/bin/grumphp run --tasks=phpcsfixer -y` ?

**Comment by FlorentTorregrosa** [comment]
Thanks for the reactivity and the hint.

I will try.

**Comment by FlorentTorregrosa** [comment]
Ok my bad, in Github results, I missed the small triangle to expand the result of the PHPCS Fixer task...

**Comment by FlorentTorregrosa** [comment]
PR ready.

**Pull request merged**
