### PR TITLE
Issue #22: Rule "escape_implicit_backslashes" is deprecated. Use "string_implicit_backslashes" instead.

### LINKED ISSUE #22: Rule "escape_implicit_backslashes" is deprecated. Use "string_implicit_backslashes" instead.
## Steps required to reproduce the problem

1. On "friendsofphp/php-cs-fixer":"v3.49.0",
2. dev version of drupol/phpcsfixer-configs-drupal,

## Expected Result

No deprecation in use.

## Actual Result

```
Detected deprecations in use:
- Rule "escape_implicit_backslashes" is deprecated. Use "string_implicit_backslashes" instead.
```

### PR DESCRIPTION
**Pull request by FlorentTorregrosa**
This PR

Follows https://github.com/drupol/phpcsfixer-configs-php/pull/62.
Fixes #22 .

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Comment by FlorentTorregrosa** [comment]
Hum, should the friendsofphp/php-cs-fixer version requirement be increased in this PR too? It will be updated in https://github.com/drupol/phpcsfixer-configs-php/pull/62, but I wonder if this be the case here too?

**Comment by FlorentTorregrosa** [comment]
Coding standards fixed in #21

**Comment by drupol** [comment]
Go for it man, you don't need me for reviewing, I fully trust you on this project.

**Comment by FlorentTorregrosa** [comment]
Thanks. PR rebased and updated.

So as for https://github.com/drupol/phpcsfixer-configs-php/pull/62#issuecomment-1945977621, I can't merge myself in this repository :)

**Pull request merged**
