### PR TITLE
refactoring of tests, Grumphp integration using PHPUnit & Github Actions & some minors fixes

### PR DESCRIPTION
**Pull request by WengerK**
## 🚧 Todos:
- [x] Remove Codeception
- [x] add PHPUnit testing
- [x] Remove Scrutinizer ?
- [x] Remove Infection
- [x] Remove Travis
- [x] Update integration of grumpphp
- [x] Update compose scripts alias
- [x] Fix Try/Catch to support Finally keyword
- [x] Fix Try/Catch Whitespaces
- [ ] ~add Psalm ?~
- [x] Remove WIP `src/Fixer/LineLengthFixer.php` (create a new PR with it)
- [x] Integrate to Github Actions
- [x] integrate PHP-CS-Fixer whitout following drup0l convention but Symfony (or any community driven) one ?
- [x] Remove NewlineAfterLastCommaInArrayFixer that is deprecated since trailing_comma_in_multiline exists on php-cs-fixer core

## 🕙 Follow-up
- [ ] add Psalm (and following needed) fixes
- [ ] Checkout faisability to re-add https://github.com/drupol/php-conventions
- [ ] open a WIP PR with original code of `src/Fixer/LineLengthFixer.php`

## 🎟️ Issues
- close https://github.com/drupol/phpcsfixer-configs-drupal/issues/4
- close https://github.com/drupol/phpcsfixer-configs-drupal/pull/11

### CODE REVIEW

**Comment by WengerK** [comment]
I'll check out how I could (re)add [drupol/php-conventions](https://github.com/drupol/php-conventions) before merging this and explain why - if I can't.

**Comment by WengerK** [comment]
Using and installing `drupol/php-conventions` would allow use to normalize the php-cs-fixer (project one) configuration of this project.

aka the following code

````
# .php-cs-fixer.dist.php
<?php

$finder = \PhpCsFixer\Finder::create()
    ->exclude('vendor')
    ->exclude(['tests/Integration/fixtures'])
    ->in(__DIR__);

$config = new \PhpCsFixer\Config();

return $config->setRules([
        '@Symfony' => true,
        'array_syntax' => ['syntax' => 'short'],
        'phpdoc_align' => ['align' => 'vertical', 'tags' => ['type', 'var']],
        'concat_space' => ['spacing' => 'one'],
        'global_namespace_import' => true,
    ])
    ->setFinder($finder)

;
```

When attempting to add it on this project, it seems `drupol/php-conventions` have some dependencies that lock version of:
- psalm
- maglnet/composer-require-checker

I'm not confident into depending on `drupol/php-conventions` 'cause it would lock this library to use a specific version of `psalm` and `maglnet/composer-require-checker`

```bash
    - drupol/php-conventions[5.1.0, ..., 5.1.2] require maglnet/composer-require-checker ^1.1 || ^2.1 || ^3.2 -> found maglnet/composer-require-checker[1.1.0, 2.1.0, 3.2.0, ..., 3.8.0] but it conflicts with your root composer.json require (^4.4.0).
    - vimeo/psalm[4.0.0, ..., 4.7.0] require composer/xdebug-handler ^1.1 -> found composer/xdebug-handler[1.1.0, ..., 1.4.6] but the package is fixed to 3.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - vimeo/psalm[4.7.1, ..., 4.16.1] require composer/xdebug-handler ^1.1 || ^2.0 -> found composer/xdebug-handler[1.1.0, ..., 1.4.6, 2.0.0, ..., 2.0.5] but the package is fixed to 3.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - psalm/phar is locked to version 5.15.0 and an update of this package was not requested.
    - drupol/php-conventions[5.1.3, ..., 5.1.4] require vimeo/psalm ^4 || ^5 -> satisfiable by vimeo/psalm[4.0.0, ..., 4.30.0, 5.0.0, ..., 5.15.0].
```

To go forward with `drupol/php-conventions`, the package itself should declare psalm & other own utilities as dev-dependency nop ?

**Comment by drupol** [comment]
Hi Kevin!

Let's remove it from now, so we can move on and you're not blocked by it.

WDYT?

**Comment by WengerK** [comment]
@FlorentTorregrosa could you try this PR on your (some) project(s) to ensure I did not create some regression ?

**Comment by FlorentTorregrosa** [comment]
Thanks @WengerK.

I have tested on the file_extractor module.

I have one problem, at the end of classes, interfaces, (OOP files), the indentation of the closing brace is 2:

```php
abstract class ExtractorPluginBase extends PluginBase implements ContainerFactoryPluginInterface, ExtractorPluginInterface {
...
  }
```

**Comment by FlorentTorregrosa** [comment]
Tested with the last push. Ok for me. Thanks!

**Comment by drupol** [comment]
I admire this energy and collaboration, thanks guys :)

**Comment by WengerK** [comment]
Many Many thanks to @FlorentTorregrosa for all the collaboration by helping @drupol and me on this huge PR.
Thanks to @drupol for having created this project some years ago and allows me to continue to maintain it.

Hopes with this PR we will be able to follow php-cs-fixer and drupal rules with confidence and ease.

I'll work on a release in few days with detailed changelog.

**Pull request merged**
